const ATTRS = ["str","dex","con","int","wis","cha"];
const ATTR_NAME = {str:"Strength",dex:"Dexterity",con:"Constitution",int:"Intelligence",wis:"Wisdom",cha:"Charisma"};
function mod(score){ return Math.floor((score-10)/2); }
function fmt(n){ return (n>=0?"+":"")+n; }

/* ---------------------------------------------------------------------
   SKILLS — the 21 skills from Chapter "Skills"
   --------------------------------------------------------------------- */
const SKILLS = [
  {id:"acrobatics", name:"Acrobatics", attr:"dex", desc:"Keep your footing on unstable ground, tumble out of the way of an attack, or squeeze through a gap you probably shouldn't fit through."},
  {id:"appraise", name:"Appraise", attr:"int", desc:"Judge the worth, condition, or usefulness of scavenged goods at a glance."},
  {id:"athletics", name:"Athletics", attr:"con", desc:"Climb, swim, jump, or grind through a physically brutal task."},
  {id:"craft", name:"Craft", attr:"int", desc:"Build, modify, or improvise items in a chosen field (Mechanic, Structural, and so on)."},
  {id:"diplomacy", name:"Diplomacy", attr:"cha", desc:"Talk people down, negotiate trades, and keep camp politics from boiling over."},
  {id:"disabledevice", name:"Disable Device", attr:"dex", desc:"Pick locks, disarm traps, and bypass security — old-world or improvised."},
  {id:"drive", name:"Drive", attr:"dex", desc:"Operate a vehicle under pressure, on bad roads, with something chasing you."},
  {id:"gatherinfo", name:"Gather Information", attr:"cha", desc:"Work a room, a bar, or a checkpoint line for rumors and news."},
  {id:"handleanimal", name:"Handle Animal", attr:"wis", desc:"Calm, train, or work alongside animals."},
  {id:"heal", name:"Heal", attr:"wis", desc:"Treat wounds, illness, and infection with whatever's on hand."},
  {id:"intimidate", name:"Intimidate", attr:"cha", desc:"Scare, threaten, or bully a target into backing down or giving something up."},
  {id:"knowledge", name:"Knowledge", attr:"int", desc:"Recall specialized information — history, mechanics, medicine, or what makes a Zombie tick."},
  {id:"melee", name:"Melee", attr:"str", desc:"Land solid hits in hand-to-hand combat."},
  {id:"perception", name:"Perception", attr:"wis", desc:"Notice threats, details, and ambushes before they notice you."},
  {id:"profession", name:"Profession", attr:"int", desc:"Apply a pre-apocalypse trade to a problem that calls for it."},
  {id:"ranged", name:"Ranged", attr:"dex", desc:"Land solid hits with a firearm, bow, or thrown weapon from a distance."},
  {id:"repair", name:"Repair", attr:"int", desc:"Fix machinery, electronics, and vehicles that have seen better days."},
  {id:"sensemotive", name:"Sense Motive", attr:"wis", desc:"Read a person's intentions, catch a lie, or get a hunch something's wrong."},
  {id:"sleightofhand", name:"Sleight of Hand", attr:"dex", desc:"Palm, plant, or lift a small object without anyone noticing."},
  {id:"stealth", name:"Stealth", attr:"dex", desc:"Move, hide, or work without being seen or heard."},
  {id:"survival", name:"Survival", attr:"wis", desc:"Forage, track, navigate, and endure harsh conditions with no safety net."},
];
const SKILL_BY_ID = Object.fromEntries(SKILLS.map(s=>[s.id,s]));

/* ---------------------------------------------------------------------
   FEATS — the core Feats list. `effects` are auto-totaled into the sheet;
   `param` marks a Feat that needs a choice (skill, or melee/ranged) when granted.
   --------------------------------------------------------------------- */
const FEATS = [
  {id:"catsreflexes", name:"Cat's Reflexes", desc:"+2 to Reflex saves — dodging traps, explosions, and collapsing structures.", effects:[{kind:"save",target:"dex",amount:2}]},
  {id:"cleanshot", name:"Clean Shot", desc:"No penalty on ranged attack rolls against a target engaged in melee with someone else.", effects:[]},
  {id:"closeinshooter", name:"Close-In Shooter", desc:"+2 to attack rolls with ranged weapons against targets within a short distance (~30 ft).", effects:[{kind:"skill",target:"ranged",amount:2,note:"close range only"}]},
  {id:"fastdraw", name:"Fast Draw", desc:"Draw or holster a weapon as a free action instead of using an action.", effects:[]},
  {id:"fasthealer", name:"Fast Healer", desc:"Recover twice the normal Health from a night's rest or medical treatment.", effects:[]},
  {id:"fieldmedic", name:"Field Medic", desc:"+2 to Heal checks, and treating a wound takes half the normal time.", effects:[{kind:"skill",target:"heal",amount:2}]},
  {id:"fleetfooted", name:"Fleet-Footed", desc:"+10 feet to Speed, and no penalty to Perception while moving at full Speed.", effects:[{kind:"derived",target:"speed",amount:10}]},
  {id:"followthrough", name:"Follow-Through", desc:"If a melee attack drops a Zombie, immediately make one free melee attack against another Zombie within reach.", effects:[]},
  {id:"gotoweapon", name:"Go-To Weapon", desc:"+2 to attack rolls made with the chosen weapon type (melee or ranged).", param:"meleeranged", effects:[{kind:"skill",target:"melee",amount:2}]},
  {id:"greenthumb", name:"Green Thumb", desc:"+2 to Survival checks made to forage or identify safe food and water.", effects:[{kind:"skill",target:"survival",amount:2,note:"foraging only"}]},
  {id:"grit", name:"Grit", desc:"+2 to Constitution-based checks and saves related to fatigue, exposure, and going without food, water, or sleep.", effects:[{kind:"save",target:"con",amount:2,note:"fatigue/exposure only"}]},
  {id:"gutfeelin", name:"Gut Feelin'", desc:"+2 to Gather Information, Perception, and Sense Motive checks.", effects:[{kind:"skill",target:"gatherinfo",amount:2},{kind:"skill",target:"perception",amount:2},{kind:"skill",target:"sensemotive",amount:2}]},
  {id:"hardtokill", name:"Hard to Kill", desc:"+2 to Health, and +2 to Constitution-based checks made to resist being knocked unconscious.", effects:[{kind:"derived",target:"health",amount:2},{kind:"save",target:"con",amount:2,note:"vs. unconsciousness only"}]},
  {id:"haymaker", name:"Haymaker", desc:"Before a melee attack roll, take −2 to the roll for +4 damage on a hit.", effects:[]},
  {id:"improvisedweaponmaster", name:"Improvised Weapon Master", desc:"No penalty when attacking with an improvised weapon, and +2 to damage with them.", effects:[]},
  {id:"intimidator", name:"The Intimidator", desc:"+2 to Drive checks made while driving aggressively.", effects:[{kind:"skill",target:"drive",amount:2,note:"aggressive driving only"}]},
  {id:"leadlinedstomach", name:"Lead-Lined Stomach", desc:"+2 to Constitution checks and Fortitude saves against spoiled, toxic, or questionable food and drink.", effects:[{kind:"save",target:"con",amount:2,note:"bad food/drink only"}]},
  {id:"macgyver", name:"MacGyver", desc:"When Crafting or Repairing something improvised, ignore the Difficulty increase for working without a Blueprint.", effects:[]},
  {id:"ninelives", name:"Nine Lives", desc:"Once per session, reroll a failed save against death or dying and take the better result.", effects:[]},
  {id:"oldhand", name:"Old Hand", desc:"+2 to the chosen Skill. Can be taken more than once for different Skills.", param:"skill", effects:[{kind:"skill",target:"perception",amount:2}]},
  {id:"packmule", name:"Pack Mule", desc:"Carry capacity increases by 50% without penalty to Speed.", effects:[{kind:"derived",target:"bulkmult",amount:0.5}]},
  {id:"quietfeet", name:"Quiet Feet", desc:"+2 to Stealth checks.", effects:[{kind:"skill",target:"stealth",amount:2}]},
  {id:"rage", name:"Rage", desc:"While active: +2 Melee attack/damage, +2 Fortitude saves, −2 Defense. Lasts until no threats remain in sight.", effects:[]},
  {id:"readtheground", name:"Read the Ground", desc:"+2 to Survival checks made to track; on a success, learn one detail about the tracked creature.", effects:[{kind:"skill",target:"survival",amount:2,note:"tracking only"}]},
  {id:"sharpeyes", name:"Sharp Eyes", desc:"+2 to Perception and Sense Motive checks.", effects:[{kind:"skill",target:"perception",amount:2},{kind:"skill",target:"sensemotive",amount:2}]},
  {id:"silvertongue", name:"Silver Tongue", desc:"+2 to Gather Information checks; NPCs need a better reason to turn hostile after a failed roll.", effects:[{kind:"skill",target:"gatherinfo",amount:2}]},
  {id:"snapreactions", name:"Snap Reactions", desc:"Take one additional reactive attack per round when a Zombie moves through your reach.", effects:[]},
  {id:"steadyhands", name:"Steady Hands", desc:"+2 to Craft and Repair checks made under pressure or with improvised tools.", effects:[{kind:"skill",target:"craft",amount:2,note:"under pressure"},{kind:"skill",target:"repair",amount:2,note:"under pressure"}]},
  {id:"steelnerve", name:"Steel Nerve", desc:"+2 to Will saves — resisting fear, despair, and outside influence.", effects:[{kind:"save",target:"wis",amount:2}]},
  {id:"vitalstrike", name:"Vital Strike", desc:"Reduce the penalty for a Called Shot by 2.", effects:[]},
  {id:"wontgodown", name:"Won't Go Down", desc:"At 0 Health, remain conscious for one action per round instead of going down immediately, until below a negative equal to Constitution score.", effects:[]},
];
const FEAT_BY_ID = Object.fromEntries(FEATS.map(f=>[f.id,f]));

/* ---------------------------------------------------------------------
   ROLES — the 24 Roles. Every Survivor picks TWO.
   abilityMod: {fixed:{attr:n}} | {choice:[attrs], amount} | {any:amount}
   skillBonuses: [{skill, amount, note}] | skillChoice:{count, amount} for player-picked skills
   featGrant: {id} | {choice:[ids]}  (each may itself need a param, resolved in UI)
   flawEffects: [{skill, amount, note}] — auto-totaled where the Flaw gives a flat number
   --------------------------------------------------------------------- */
const ROLES = [
  {id:"averagejoe", name:"Average Joe", hook:"Ordinary folks with surprisingly good instincts",
   blurb:"Normal, everyday people trained to do normal, everyday things. Being “average” ain’t always a bad thing.",
   abilityMod:{any:1}, skillChoice:{count:2, amount:2},
   special:{name:"Gut Feeling", desc:"Once per session, treat a failed Wisdom-based check as a success."},
   featGrant:{id:"oldhand"},
   flaw:"No bonus beyond the above — no innate specialty to fall back on.", flawEffects:[],
   kit:"Whatever was in the car or the junk drawer — a little cash, a phone, half a tank of gas."},
  {id:"builder", name:"Builder", hook:"Fortifies gates, patches roofs, rigs traps",
   blurb:"Fortifies gates, patches roofs, rigs traps — the reason the walls are still standing.",
   abilityMod:{choice:["str","int"], amount:2}, skillBonuses:[{skill:"craft",amount:6,note:"structural"}],
   special:{name:"Sturdy Work", desc:"A structure, trap, or fortification they build grants allies +2 AC or a +4 bonus on a relevant defense check for the scene."},
   featGrant:{id:"oldhand", forceParam:"craft"},
   flaw:"−2 to initiative or Speed in the field — slow, weighed down by tools.", flawEffects:[{derived:"speed",amount:-2,note:"or initiative, player's choice"}],
   kit:"A well-worn toolbox and scraps saved from a dozen different ruins."},
  {id:"combatant", name:"Combatant", hook:"Trained fighter, close combat or ranged",
   blurb:"The modern-day warriors. Trained in close combat, ranged combat, or a mix of both.",
   abilityMod:{choice:["str","dex"], amount:2}, skillBonuses:[{skill:"perception",amount:4},{skill:"intimidate",amount:2}],
   special:{name:"Tactical Read", desc:"Once per encounter, as a swift action, grant the group +2 to attack rolls for one round."},
   featGrant:{choice:["closeinshooter","gotoweapon"]},
   flaw:"−2 to checks made without a clear plan or chain of command.", flawEffects:[],
   kit:"Sidearm, a few spare mags, and a uniform or gear that says “don't try me.”"},
  {id:"thedamaged", name:"The Damaged", hook:"Hardened by a rough life before the fall",
   blurb:"People who've led hard and unfair lives and still made it out the other side.",
   abilityMod:{fixed:{con:2}}, saveBonuses:[{save:"wis",amount:4,note:"vs. fear and despair only"}],
   special:{name:"Rock Bottom", desc:"Once per session, ignore a wound penalty or fear effect for one scene."},
   featGrant:{id:"grit"},
   flaw:"−2 Diplomacy and Sense Motive in “normal” social situations.", flawEffects:[{skill:"diplomacy",amount:-2,note:"normal social situations"},{skill:"sensemotive",amount:-2,note:"normal social situations"}],
   kit:"Whatever they walked in with — usually not much, and usually a habit they're fighting."},
  {id:"deadeye", name:"Deadeye", hook:"One shot, one problem solved",
   blurb:"Doesn't waste a bullet. One shot, one problem solved, from a distance most folks couldn't hit a barn from.",
   abilityMod:{fixed:{dex:2}}, skillBonuses:[{skill:"ranged",amount:6}],
   special:{name:"Perfect Shot", desc:"Once per session, a called shot with a ranged weapon automatically hits and drops a target (GM discretion on tougher targets)."},
   featGrant:{choice:["closeinshooter","cleanshot"]},
   flaw:"−4 to attack rolls when out of ammo or without a ranged weapon.", flawEffects:[],
   kit:"A rifle they trust with their life, and never enough ammo for it."},
  {id:"driver", name:"Driver", hook:"Calm, sharp, three moves ahead behind the wheel",
   blurb:"Behind the wheel, they're a different person — calm, sharp, and always three moves ahead.",
   abilityMod:{fixed:{dex:2}}, skillBonuses:[{skill:"drive",amount:6}],
   special:{name:"Pedal to the Metal", desc:"Once per session, automatically succeed on a driving maneuver, no matter how reckless."},
   featGrant:{id:"oldhand", forceParam:"drive"},
   flaw:"−2 to all rolls while on foot — exposed without a vehicle.", flawEffects:[],
   kit:"Their ride — patched, loud, and running on fumes and stubbornness."},
  {id:"enforcer", name:"Enforcer", hook:"Keeps order the hard way",
   blurb:"Every camp needs someone the troublemakers are scared of, and someone the rest can sleep easy knowing is on watch.",
   abilityMod:{fixed:{str:2}}, skillBonuses:[{skill:"intimidate",amount:4}],
   special:{name:"Iron Fist", desc:"Once per encounter, a successful melee hit forces a Will save or the target flees or surrenders."},
   featGrant:{id:"hardtokill"},
   flaw:"−2 Diplomacy — feared more than liked.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"Whatever weapon earned them the job, kept close at all times."},
  {id:"greasemonkey", name:"Grease Monkey", hook:"Keeps every engine running past its time",
   blurb:"Keeps every engine, cart, and busted-up truck running long past when it should've died.",
   abilityMod:{choice:["int","dex"], amount:2}, skillBonuses:[{skill:"craft",amount:6,note:"mechanic"},{skill:"repair",amount:6}],
   special:{name:"Field Fix", desc:"Once per session, repair a vehicle enough to run for one more scene, no matter how damaged."},
   featGrant:{id:"oldhand", forceParam:"craft"},
   flaw:"Depends on scavenged parts to keep working (GM adjudicated when supply runs thin).", flawEffects:[],
   kit:"A greasy toolbox and an eye for spotting the one part that'll actually work."},
  {id:"gungho", name:"Gung-ho", hook:"Runs toward the gunfire, not away from it",
   blurb:"Runs toward the gunfire while everyone else runs away. Reckless as hell, but somebody's gotta do it.",
   abilityMod:{fixed:{str:2}}, skillBonuses:[{skill:"intimidate",amount:4}],
   special:{name:"Adrenaline Rush", desc:"Once per encounter, ignore all wound penalties for one round."},
   featGrant:{id:"wontgodown"},
   flaw:"Must make a Will save to avoid charging into danger recklessly.", flawEffects:[],
   kit:"Whatever weapon's closest, usually held wrong but swung with total confidence."},
  {id:"hero", name:"Hero", hook:"People follow, for better or worse",
   blurb:"Whatever they say, people listen. Whatever they do, people follow.",
   abilityMod:{fixed:{cha:2}}, skillBonuses:[{skill:"diplomacy",amount:4}],
   special:{name:"Rally", desc:"Once per session, remove a fear or despair effect from the whole group."},
   featGrant:{id:"steelnerve"},
   flaw:"Enemies get +2 to notice or target them — a painted target.", flawEffects:[],
   kit:"Nothing special, and yet somehow everyone still looks to them."},
  {id:"homesteader", name:"Homesteader", hook:"Built a real home out of nothing",
   blurb:"Built a life out of nothing — crops, walls, a real community. The reason a camp becomes a home.",
   abilityMod:{choice:["cha","wis"], amount:2}, skillBonuses:[{skill:"diplomacy",amount:4},{skill:"craft",amount:2}],
   special:{name:"Steady Hand", desc:"Once per session, remove a despair or fear effect from the group during a long, hard stretch."},
   featGrant:{id:"oldhand", forceParam:"diplomacy"},
   flaw:"−2 Melee and Ranged — non-combatant.", flawEffects:[{skill:"melee",amount:-2},{skill:"ranged",amount:-2}],
   kit:"Whatever it takes to keep a home running — tools, seeds, and a stubborn will."},
  {id:"marauder", name:"Marauder", hook:"Takes what they want — rules don't apply anymore",
   blurb:"Takes what they want because the old rules don't apply anymore. Not evil, necessarily — just done asking nicely.",
   abilityMod:{fixed:{str:2}}, skillBonuses:[{skill:"intimidate",amount:4}],
   special:{name:"Show of Force", desc:"Once per encounter, a display of violence forces a Will save or the target backs down."},
   featGrant:{id:"haymaker"},
   flaw:"−2 Diplomacy — feared, not trusted.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"Whatever was worth taking, plus a weapon they're not afraid to use."},
  {id:"medic", name:"Medic", hook:"Keeps the group breathing",
   blurb:"Nurse, vet, or just paid attention in health class — the Medic keeps the group breathing.",
   abilityMod:{fixed:{wis:2}}, skillBonuses:[{skill:"heal",amount:6}],
   special:{name:"Stabilize", desc:"Once per session, automatically stabilize a dying ally regardless of conditions."},
   featGrant:{id:"oldhand", forceParam:"heal"},
   flaw:"−2 Melee and Ranged; no proficiency beyond simple weapons.", flawEffects:[{skill:"melee",amount:-2},{skill:"ranged",amount:-2}],
   kit:"A dwindling med kit, always running low on the stuff that actually matters."},
  {id:"naturalist", name:"Naturalist", hook:"Farms, forages, keeps the camp fed",
   blurb:"Farms, forages, and keeps animals alive in a world that's trying to kill everything.",
   abilityMod:{fixed:{wis:2}}, skillBonuses:[{skill:"survival",amount:6,note:"foraging"},{skill:"handleanimal",amount:6}],
   special:{name:"Bountiful Find", desc:"Once per session, turn up a real meal or a useful plant or animal when it's needed most."},
   featGrant:{id:"oldhand", forceParam:"survival"},
   flaw:"Results take time — no immediate benefit in a crisis.", flawEffects:[],
   kit:"Seeds, snares, and a working knowledge of what's safe to eat."},
  {id:"prepper", name:"Prepper", hook:"Ready for anything, stocked and paranoid",
   blurb:"Survivalist? Paranoid? These are the people who won't starve once the local market's picked clean.",
   abilityMod:{fixed:{wis:2}}, skillBonuses:[{skill:"survival",amount:4},{skill:"craft",amount:2}],
   special:{name:"Contingency Plan", desc:"Once per scenario, reveal a mundane item as though packed for exactly this situation (GM approval)."},
   featGrant:{id:"oldhand", forceParam:"survival"},
   flaw:"−2 Diplomacy — distrustful of new people.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"A stash — rations, tools, a hidden cache somewhere they're not telling anyone about yet."},
  {id:"profiler", name:"Profiler", hook:"Reads people — and Zombies — like a hawk",
   blurb:"Watches people and zombies like a hawk, reading tells and patterns until they know what's coming.",
   abilityMod:{choice:["int","wis"], amount:2}, skillBonuses:[{skill:"sensemotive",amount:6}],
   special:{name:"Called It", desc:"Once per session, correctly predict an enemy's next action, granting the group a +4 bonus to react to it."},
   featGrant:{id:"oldhand", forceParam:"sensemotive"},
   flaw:"−2 Diplomacy — detached, struggles to connect emotionally.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"A notebook of observations on everyone they've ever met — living or dead."},
  {id:"rogue", name:"Rogue", hook:"Gets in, gets out, unnoticed",
   blurb:"Thief, con artist, grifter — they get in, get out, and get what they came for without anybody the wiser.",
   abilityMod:{fixed:{dex:2}}, skillBonuses:[{skill:"stealth",amount:6},{skill:"disabledevice",amount:2}],
   special:{name:"Slip Away", desc:"Once per session, automatically escape a bad situation unnoticed, and may bring one ally along."},
   featGrant:{id:"oldhand", forceParam:"stealth"},
   flaw:"−2 Diplomacy — other survivors are slow to trust them with anything important.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"Lock picks, a fast tongue, and something they probably stole from someone in the group."},
  {id:"savant", name:"Savant", hook:"Turns a losing fight into a plan",
   blurb:"Never held a gun before the world ended, but reads a situation like nobody's business.",
   abilityMod:{fixed:{int:2}}, skillBonuses:[{skill:"knowledge",amount:4},{skill:"sensemotive",amount:2}],
   special:{name:"Master Plan", desc:"Once per session, grant the whole group a +2 circumstance bonus on a related roll for the rest of the scene."},
   featGrant:{id:"oldhand", forceParam:"knowledge"},
   flaw:"−2 Str-based checks — physically weak.", flawEffects:[{skill:"melee",amount:-2,note:"Str-based"},{skill:"athletics",amount:-2,note:"Str-based"}],
   kit:"Notes, maps, and a memory that doesn't forget a mistake."},
  {id:"scavenger", name:"Scavenger", hook:"Finds what everyone else missed",
   blurb:"A knack for finding useful things others discarded, or turning junk into something useful.",
   abilityMod:{fixed:{dex:2}}, skillBonuses:[{skill:"perception",amount:4},{skill:"appraise",amount:2}],
   special:{name:"Nothing Wasted", desc:"Once per session, produce one small mundane item as if scavenged on the spot."},
   featGrant:{id:"oldhand", forceParam:"perception"},
   flaw:"−2 to melee attack rolls.", flawEffects:[{skill:"melee",amount:-2}],
   kit:"A patched-together bag of odds and ends and a knife that's seen better days."},
  {id:"specialist", name:"Specialist", hook:"Expert in one trained field",
   blurb:"Highly trained in one area — doctors, engineers, even artists; people who've dedicated their lives to one thing.",
   abilityMod:{fixed:{int:2}}, skillChoice:{count:1, amount:6, from:["craft","knowledge","profession"]},
   special:{name:"Expert Solution", desc:"Once per session, automatically succeed on a skill check within their field."},
   featGrant:{id:"oldhand", forceParam:null},
   flaw:"−2 Str-based checks; no proficiency beyond simple weapons.", flawEffects:[{skill:"melee",amount:-2,note:"Str-based"},{skill:"athletics",amount:-2,note:"Str-based"}],
   kit:"Tools of the trade — a med kit, toolkit, art supplies, or a notebook full of specialized knowledge."},
  {id:"techie", name:"Techie", hook:"Gets the old world's junk humming again",
   blurb:"Cracks locks, rewires generators, gets the old world's junk humming again.",
   abilityMod:{fixed:{int:2}}, skillBonuses:[{skill:"disabledevice",amount:6},{skill:"craft",amount:6,note:"mechanical"}],
   special:{name:"Jury-Rig", desc:"Once per session, get broken technology or a vehicle working again, temporarily, no matter how damaged."},
   featGrant:{id:"oldhand", forceParam:"disabledevice"},
   flaw:"−2 Diplomacy — more comfortable with wires than with people.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"A rat's nest of cables, tools, and salvaged parts."},
  {id:"tracker", name:"Tracker", hook:"Reads the land — sees it coming first",
   blurb:"Learned to read footprints, broken branches, and the smell of rot on the wind.",
   abilityMod:{fixed:{wis:2}}, skillBonuses:[{skill:"survival",amount:6,note:"tracking"}],
   special:{name:"On the Trail", desc:"Once per session, automatically find a trail or sign that would otherwise be missed."},
   featGrant:{id:"oldhand", forceParam:"survival"},
   flaw:"−2 Diplomacy — more at home in the wild than in a camp full of strangers.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"A well-worn set of boots and a knife made for skinning, not fighting."},
  {id:"vulture", name:"Vulture", hook:"Loots the dead without apology",
   blurb:"Learned fast that the dead — both kinds — carry things the living need.",
   abilityMod:{fixed:{dex:2}}, skillBonuses:[{skill:"perception",amount:4},{skill:"stealth",amount:2}],
   special:{name:"Grim Find", desc:"Once per session, looting a body or ruin turns up something valuable (GM approval)."},
   featGrant:{id:"oldhand", forceParam:"perception"},
   flaw:"−2 Diplomacy — poor reputation among other survivors.", flawEffects:[{skill:"diplomacy",amount:-2}],
   kit:"A sack full of trinkets, ammo, and gear pulled off folks who don't need it anymore."},
  {id:"zealot", name:"Zealot", hook:"True believer — saves souls or ends them",
   blurb:"Before the fall, already over the top in their faith. Now the actual end has come.",
   abilityMod:{choice:["wis","cha"], amount:2}, skillChoice:{count:1, amount:4, from:["diplomacy","intimidate"]},
   special:{name:"Judgment", desc:"Once per session, an attempt to save or eliminate a target succeeds automatically; the player chooses the outcome, the GM narrates the consequences."},
   featGrant:{id:"steelnerve"},
   flaw:"Fanaticism — the GM may compel the Zealot toward an extreme action once per session.", flawEffects:[],
   kit:"A symbol of their faith and a following, however small, that trusts their word."},
];
const ROLE_BY_ID = Object.fromEntries(ROLES.map(r=>[r.id,r]));

/* ---------------------------------------------------------------------
   STARTING KITS — Chapter Five's eight concrete kits
   --------------------------------------------------------------------- */
const KITS = [
  {id:"bugout", name:"Bug-Out Bag", quote:"Grab it and go. Don't stop to think, don't stop to pack.", items:["Backpack","Kitchen Knife","Canned Food (x3)","Water Filter","Flashlight & Batteries","Duct Tape"]},
  {id:"roadwarrior", name:"Road Warrior Kit", quote:"For folks who live by the wheels under 'em.", items:["Machete","Handgun (6 rounds)","Map & Compass","Duct Tape","a half-empty gas can"]},
  {id:"campmedic", name:"Camp Medic's Bag", quote:"Ain't pretty. Keeps people breathin' though.", items:["Med Kit","Painkillers","Antibiotics","Booze (for “sterilizing”)","Rope"]},
  {id:"scavenger", name:"Scavenger's Pack", quote:"Half the job's carrying it out. This is for that half.", items:["Backpack","Sharpened Rebar","Flashlight & Batteries","empty sacks for hauling loot","a lucky trinket (no mechanical effect)"]},
  {id:"homesteader", name:"Homesteader's Toolbox", quote:"Building's slower than breaking. Worth it though.", items:["Tool Kit","Duct Tape","Rope","a handful of seeds","a well-worn hammer (treat as Baseball Bat)"]},
  {id:"watch", name:"Watch Kit", quote:"Somebody's gotta stay up. Might as well not be miserable doin' it.", items:["Hunting Rifle or Crossbow","Hand-Crank Radio","Map & Compass","a thermos of bad coffee"]},
  {id:"comfort", name:"Comfort Kit", quote:"This is the kit that don't kill zombies. Kills the quiet, though.", items:["Chewing Gum","Cigarettes","a deck of cards","one Coffee / Energy Drink"]},
  {id:"fortressdefender", name:"Fortress Defender's Kit", quote:"Walls only hold if somebody behind 'em can still fight.", items:["Riot Gear","Shotgun","Molotov Cocktail (x2)","Med Kit"]},
];
const KIT_BY_ID = Object.fromEntries(KITS.map(k=>[k.id,k]));
const ROLE_KIT_SUGGESTION = {averagejoe:"bugout",combatant:"roadwarrior",prepper:"bugout",scavenger:"scavenger",vulture:"scavenger",medic:"campmedic",builder:"homesteader",enforcer:"fortressdefender",techie:null,homesteader:"homesteader",naturalist:"homesteader",deadeye:"watch",tracker:"watch"};

/* ---------------------------------------------------------------------
   EQUIPMENT — Chapter Five reference lists (for the optional custom loadout)
   --------------------------------------------------------------------- */
const WEAPONS = {
  "Handguns": [
    ["Glock 17 (9mm)","1d8","Close","Quiet","17 box","1.5 lb"],["Beretta 92F (9mm)","1d8","Close","Quiet","15 box","2 lb"],
    ["M1911 (.45 ACP)","1d8","Close","Quiet","7 box","2.5 lb"],["Glock 21 (.45 ACP)","1d8","Close","Quiet","13 box","2 lb"],
    ["Glock 22 (.40 S&W)","1d8","Close","Quiet","15 box","2 lb"],["Desert Eagle (.50 AE)","1d10","Close","Quiet","8 box","4.5 lb"],
    ["Revolver (.38 Special)","1d8","Close","Quiet","6 cyl","2 lb"],["Colt Python (.357 Magnum)","1d8","Close","Quiet","6 cyl","2.5 lb"],
    ["S&W Model 29 (.44 Magnum)","1d10","Close","Quiet","6 cyl","3 lb"],["Glock 26 (compact 9mm)","1d8","Close","Quiet","10 box","1.3 lb"],
    ["Snub-Nosed Revolver (.38)","1d8","Close","Quiet","6 cyl","1.3 lb"],["Pocket Derringer (.45)","1d6","Close","Quiet","2 int.","0.5 lb"],
    ["TEC-9 (9mm, full-auto)","1d8","Close","Loud","30 box","3.5 lb"],["MAC-10 / Ingram (.45 ACP)","1d8","Close","Loud","30 box","3.5 lb"],
  ],
  "Submachine Guns": [
    ["MP5 (9mm)","1d8","Close","Loud","30 box","5.5 lb"],["Uzi (9mm)","1d8","Close","Loud","25 box","7.7 lb"],
    ["UMP45 (.45 ACP)","1d10","Close","Loud","25 box","6 lb"],["MP5K (compact 9mm)","1d8","Close","Loud","15 box","4.4 lb"],
  ],
  "Rifles": [
    ["Winchester Model 94 (.30-30)","1d10","Long","Loud","6 int.","7 lb"],["Remington 700 (.308/.30-06)","1d10","Long","Loud","4 int.","7.5 lb"],
    ["AR-15 / M4 (5.56mm)","1d10","Long","Loud","30 box","6.5 lb"],["M16 (5.56mm)","1d10","Long","Loud","30 box","7.5 lb"],
    ["AK-47 / AKM (7.62x39mm)","1d10","Long","Loud","30 box","7.7 lb"],["FN FAL (7.62x51mm)","2d6","Long","Loud","20 box","9.5 lb"],
    ["M14 (7.62x51mm)","2d6","Long","Loud","20 box","9.2 lb"],["HK G3 (7.62x51mm)","2d6","Long","Loud","20 box","9.7 lb"],
    ["SVD Dragunov (7.62x54R)","2d6","Long","Loud","10 box","9.5 lb"],["M110 (7.62x51mm)","2d6","Long","Loud","20 box","9.9 lb"],
    ["HK PSG1 (7.62x51mm)","2d6","Long","Loud","20 box","17.6 lb"],["M4 Carbine (5.56mm)","1d8","Long","Loud","30 box","6.4 lb"],
    ["Steyr AUG (5.56mm)","1d10","Long","Loud","30 box","8 lb"],
  ],
  "Sniper Rifles": [["Remington 700 (.308)","1d10","Long","Loud","4 int.","7.5 lb"],["Barrett M82 (.50 BMG)","2d8","Long","Deafening","10 box","30 lb"]],
  "Shotguns": [
    ["Remington 870 (12ga)","2d6","Close","Deafening","6 int.","7.5 lb"],["Mossberg 500 (12ga)","2d6","Close","Deafening","6 int.","7.3 lb"],
    ["Benelli M4 (12ga)","2d6","Close","Deafening","5 int.","7.8 lb"],["Break-Action (12ga)","2d6","Close","Deafening","1–2 int.","6.5 lb"],
    ["Sawed-Off Shotgun (12ga)","2d6","Close","Deafening","2 int.","5 lb"],
  ],
  "LMG / HMG": [["M249 SAW (5.56mm)","2d6","Long","Deafening","200 belt","17 lb"],["RPK (7.62x39mm)","2d6","Long","Deafening","75 drum","11 lb"],["M2 Browning (.50 cal, mounted)","2d8","Long","Deafening","Linked","84 lb"]],
  "Heavy / Explosives": [
    ["Fragmentation Grenade","2d8","Close","Deafening","1","1 lb"],["Molotov Cocktail","1d6","Close","Loud","1","1 lb"],
    ["RPG-7","2d8","Long","Deafening","1","15 lb"],["M72 LAW","2d8","Long","Deafening","1","5 lb"],
    ["M79 “Thumper” (40mm)","1d10","Medium","Deafening","1 int.","6.5 lb"],["Demolition Charges (C4)","6d6","Close","Deafening","—","1 lb/blk"],
  ],
  "Melee — Blades": [["Straight Razor","1d3","Melee","Silent","—","0.1 lb"],["Kukri","1d4","Melee","Silent","—","0.9 lb"],["Kitchen Cleaver","1d4","Melee","Silent","—","1 lb"],["Machete","1d6","Melee","Silent","—","1.5 lb"],["Axe / Hatchet","1d6","Melee","Silent","—","3 lb"],["Fire Axe","1d8","Melee","Silent","—","6 lb"],["Katana (jackpot find)","2d6","Melee","Silent","—","2.5 lb"],["Chain Saw (jackpot find)","2d8","Melee","Deafening","—","12 lb"]],
  "Melee — Knives": [["Kitchen Knife","1d3","Melee","Silent","—","0.3 lb"],["Folding Knife","1d3","Melee","Silent","—","0.3 lb"],["Combat Knife","1d4","Melee","Silent","—","0.5 lb"],["Fixed-Blade Hunting Knife","1d4","Melee","Silent","—","0.7 lb"],["Sharpened Rebar","1d4","Melee","Silent","—","2 lb"]],
  "Melee — Blunt": [["Tire Iron","1d4","Melee","Silent","—","2.5 lb"],["Police Baton","1d4","Melee","Silent","—","1.5 lb"],["Metal Pipe","1d4","Melee","Silent","—","3 lb"],["Baseball Bat","1d6","Melee","Silent","—","2 lb"],["Crowbar","1d6","Melee","Silent","—","5 lb"],["Sledgehammer (Str 14+, else −2)","1d10","Melee","Silent","—","10 lb"]],
  "Other": [["Compound Bow","1d6","Medium","Silent","—","4 lb"],["Recurve Bow","1d6","Medium","Silent","—","3 lb"],["Crossbow","1d6","Medium","Silent","1","7 lb"],["Flamethrower","1d6/rd","Close","Loud","10 int.","50 lb"],["Taser / Stun Gun (non-lethal)","Special","Close","Silent","1","0.5 lb"],["Pepper Spray (non-lethal)","Special","Close","Silent","1","0.3 lb"]],
};
const ARMOR = {
  "Head": [["Ballistic Helmet","+1","—","3 lb"],["Face / Eye Protection","+1","—","1 lb"],["Football Helmet","+1","—","4 lb"],["Hockey Helmet (with cage)","+1","—","2.5 lb"],["Motorcycle Helmet (full-face)","+1","—","3.5 lb"]],
  "Torso": [["Soft Body Armor (Kevlar)","+2","—","4 lb"],["Hard Armor Plates","+3","−2","8 lb"],["Plate Carrier / Chest Rig (empty)","+1","—","3 lb"],["Improvised Armor (jacket, pads)","+1","—","5 lb"],["Football Shoulder Pads","+2","−1","6 lb"],["Hockey Chest Protector","+2","−1","5 lb"],["Catcher's / Umpire Chest Protector","+2","—","4 lb"],["NBC / Hazmat Suit","+1","−1","6 lb"]],
  "Arms": [["Cut-Resistant Gloves","+1","—","0.5 lb"],["Hockey/Lacrosse Forearm Guards","+1","—","1 lb"],["Football Elbow/Arm Pads","+1","—","1.5 lb"],["Armored Motorcycle Jacket (sleeves)","+1","—","2 lb"]],
  "Legs / Feet": [["Tactical / Steel-Toe Boots","+1","—","3 lb"],["Football/Hockey Shin Guards","+1","—","1.5 lb"],["Hockey Goalie Leg Pads","+2","−1","6 lb"],["Motorcycle Riding Boots","+1","—","2.5 lb"]],
  "Shield": [["Riot Shield (raised, one attack)","+2","—","10 lb"]],
};

/* =========================================================================
   STATE
   ========================================================================= */
const STEP_LIST = [
  {id:"roles", label:"Pick Two Roles"},
  {id:"attrs", label:"Attributes"},
  {id:"skills", label:"Skills"},
  {id:"feats", label:"Feats & Flaws"},
  {id:"kit", label:"Choose a Kit"},
  {id:"details", label:"Final Details"},
  {id:"sheet", label:"Character Sheet"},
];


module.exports = {
  ATTRS, ATTR_NAME, mod, fmt,
  SKILLS, SKILL_BY_ID,
  FEATS, FEAT_BY_ID,
  ROLES, ROLE_BY_ID,
  KITS, KIT_BY_ID, ROLE_KIT_SUGGESTION,
  WEAPONS, ARMOR,
  STEP_LIST,
};
